export const villains = {
  info: {
    currentPage: 1,
    count: 318,
    pages: 16,
  },
  result: [
    {
      id: 'Abegawa_Tenchu_Kai',
      name: null,
      alias: null,
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        'Abegawa Tenchu Kai (阿辺川天忠會, Abegawa Tenchū-kai?) was a former Yakuza organization appearing in My Hero Academia: Vigilantes.',
      fightstyle: null,
      gender: null,
      Eye: null,
      hair: null,
      height: null,
      kanji: '阿辺川天忠會',
      occupation: 'Yakuza',
      quirk: null,
      romaji: 'Abegawa Tenchū-kai',
      status: 'Disbanded',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Abegawa_Tenchu_Kai-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Abegawa_Tenchu_Kai.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Air_Jet',
      name: 'Air Jet',
      alias: 'Buster Hero',
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        'Buster Hero: Air Jet (バスターヒーロー エアジェット, Basutā Hīrō Eajetto?) is a Pro Hero.',
      fightstyle: null,
      gender: null,
      Eye: null,
      hair: null,
      height: null,
      kanji: 'エアジェット',
      occupation: 'Pro Hero',
      quirk: null,
      romaji: 'Eajetto',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Air_Jet-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Air_Jet.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Akira_Iwako',
      name: 'Akira Iwako',
      alias: 'Stone Villain',
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        'Akira Iwako (岩 (いわ) 甲 (こう) 晶 (あきら) , Iwakō Akira?) was one of the Instant Villains.',
      fightstyle: null,
      gender: 'Male',
      Eye: null,
      hair: 'Black',
      height: null,
      kanji: '岩 (いわ) 甲 (こう) 晶 (あきら) ',
      occupation: 'Instant Villain',
      quirk: 'Unnamed Hardening Quirk',
      romaji: 'Iwakō Akira',
      status: 'Deceased',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Akira_Iwako-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Akira_Iwako.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'All_For_One',
      name: 'All For One',
      alias: 'Master',
      affiliation: 'League of Villains',
      birthday: null,
      bloodtype: 'B',
      description:
        "This article is about the character. For this character's Quirk, see All For One (Quirk)\nAll For One (オール・フォー・ワン, Ōru Fō Wan?), real name Shigaraki (死 (し) 柄 (がら) 木 (き) , Shigaraki?), was the former leader and benefactor of the League of Villains, the main antagonist of the Hideout Raid Arc and the overarching antagonist of the series.\nOnce Japan's most powerful villain and All Might's arch-nemesis, his true motives are unclear and his true identity is unknown. His current goal is to raise Tomura to become his eventual successor. \nHe is currently under police custody and imprisoned in Tartarus.",
      fightstyle: null,
      gender: 'Male',
      Eye: 'Unknown',
      hair: 'White (Formerly)',
      height: null,
      kanji: 'オール・フォー・ワン',
      occupation: 'Villain, Leader of the , League of Villains',
      quirk: 'All For One, Various stolen Quirks',
      romaji: 'Ōru Fō Wan',
      status: 'Imprisoned',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/All_For_One-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/All_For_One-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/All_For_One-3.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/All_For_One.jpg',
      ],
      epithet: '"Symbol of Evil',
      ages: null,
      family: [
        {
          id: 'Tomura_Shigaraki',
          name: 'Tomura Shigaraki',
        },
      ],
    },
    {
      id: 'Amplifier',
      name: 'Amplifier',
      alias: null,
      affiliation: null,
      birthday: 'June 27',
      bloodtype: null,
      description:
        'Amplifier (増幅器, Zōfukuki?) is a Pro Hero who appears in My Hero Academia: Two Heroes',
      fightstyle: null,
      gender: 'Female',
      Eye: 'Honey Brown',
      hair: 'Honey Brown',
      height: '173 cm (5\'8")',
      kanji: '増幅器',
      occupation: 'Pro Hero',
      quirk: 'Yell',
      romaji: 'Zōfukuki',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Amplifier-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Amplifier.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Aorio_Kuraishisu',
      name: 'Aorio Kuraishisu',
      alias: null,
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        'Aorio Kuraishisu (暗 (くら) 井 (い) 指 (し) 数 (す) 煽 (あおり) 雄 (お) , Kuraishisu Aorio?) is a Hero Expert.',
      fightstyle: null,
      gender: 'Male',
      Eye: null,
      hair: null,
      height: null,
      kanji: '暗 (くら) 井 (い) 指 (し) 数 (す) 煽 (あおり) 雄 (お) ',
      occupation: 'Hero Expert',
      quirk: null,
      romaji: 'Kuraishisu Aorio',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Aorio_Kuraishisu-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Aorio_Kuraishisu.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Atsuhiro_Sako',
      name: 'Atsuhiro Sako',
      alias: 'Mr. Compress',
      affiliation: 'League of Villains',
      birthday: null,
      bloodtype: null,
      description:
        "Atsuhiro Sako (迫 (さこ) 圧 (あつ) 紘 (ひろ) , Sako Atsuhiro?), also known as Mr. Compress (Mr. (ミスター) コンプレス, Misutā Konpuresu?), is a villain affiliated with the League of Villains and was a member of the organization's Vanguard Action Squad. A nationwide wanted thief, he is seen as one of the more 'experienced' members of the league. He and the rest of his team serve as the main antagonists of the Forest Training Camp Arc. \nHe later became one of the nine lieutenants of the Paranormal Liberation Front, an organization formed from the remnants of the League and the Meta Liberation Army.\nMr. Compress currently serves as a commander for the \"Vanguard Action Support Regiment: Brown\" along with Spinner.",
      fightstyle: null,
      gender: 'Male',
      Eye: 'Brown',
      hair: null,
      height: null,
      kanji: '迫 (さこ) 圧 (あつ) 紘 (ひろ) ',
      occupation:
        'Villain, Paranormal Liberation Front Lieutenant, Co-commander of the Brown Regiment, )',
      quirk: 'Compress',
      romaji: 'Sako Atsuhiro',
      status: 'Alive',
      teams: 'Vanguard Action Squad,  (Formerly), Brown Regiment',
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Atsuhiro_Sako-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Atsuhiro_Sako.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Backdraft',
      name: 'Backdraft',
      alias: null,
      affiliation: 'Musutafu Fire Department',
      birthday: 'March 7th',
      bloodtype: 'A',
      description:
        'Backdraft (バックドラフト, Bakkudorafuto?) is a Pro Hero. He works at the Musutafu Fire Department.',
      fightstyle: null,
      gender: 'Male',
      Eye: null,
      hair: null,
      height: null,
      kanji: 'バックドラフト',
      occupation: 'Pro Hero, Firefighter',
      quirk: 'Unnamed Water Quirk',
      romaji: 'Bakkudorafuto',
      status: 'Unknown',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Backdraft-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Backdraft.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Bat_Villain',
      name: 'Bat Villain',
      alias: 'Bat Villain',
      affiliation: 'Next-Level Villains',
      birthday: null,
      bloodtype: null,
      description:
        'Bat Villain (コウモリヴィラン, Kōmori Viran?) was an independent villain that was turned into a Next-Level Villain by the Villain Factory. He is from My Hero Academia: Vigilantes.',
      fightstyle: null,
      gender: 'Male',
      Eye: null,
      hair: null,
      height: null,
      kanji: null,
      occupation: 'Villain',
      quirk: 'Bat',
      romaji: null,
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bat_Villain-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bat_Villain-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bat_Villain.jpg',
      ],
      epithet: 'Mad Bat',
      ages: null,
      family: null,
    },
    {
      id: 'Bearhead',
      name: null,
      alias: null,
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description: null,
      fightstyle: null,
      gender: null,
      Eye: null,
      hair: null,
      height: null,
      kanji: null,
      occupation: null,
      quirk: null,
      romaji: null,
      status: null,
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bearhead.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Bee%E2%98%86Pop',
      name: 'Bee☆Pop',
      alias: null,
      affiliation: 'Villain Factory',
      birthday: null,
      bloodtype: null,
      description:
        "For this subject's previous identity, see Kuin Hachisuka.\nBee☆Pop (BEE☆ポップ, Bī☆Poppu?) is a villain in the spin-off My Hero Academia: Vigilantes. With her Queen Bee Quirk, she possessed Kazuho Haneyama.",
      fightstyle: null,
      gender: 'Female',
      Eye: 'Blue',
      hair: 'Pink',
      height: null,
      kanji: 'BEE☆ポップ',
      occupation: 'Villain',
      quirk: 'Queen Bee, Leap',
      romaji: 'Bī☆Poppu',
      status: 'Alive',
      teams: 'Villain Factory',
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bee%E2%98%86Pop-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bee%E2%98%86Pop-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bee%E2%98%86Pop.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Beru_Asui',
      name: 'Beru Asui',
      alias: null,
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        "Beru Asui (蛙 (あ) 吹 (すい) 鈴 (ベル) , Asui Beru?) is Tsuyu Asui's mother and the wife of Ganma Asui.",
      fightstyle: null,
      gender: 'Female',
      Eye: 'Black',
      hair: 'Dark Green',
      height: null,
      kanji: '蛙 (あ) 吹 (すい) 鈴 (ベル) ',
      occupation: null,
      quirk: null,
      romaji: 'Asui Beru',
      status: null,
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Beru_Asui-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Beru_Asui.jpg',
      ],
      epithet: null,
      ages: null,
      family: [
        {
          id: 'Ganma_Asui',
          name: 'Ganma Asui',
        },
        {
          id: 'Tsuyu_Asui',
          name: 'Tsuyu Asui',
        },
        {
          id: 'Samidare_Asui',
          name: 'Samidare Asui',
        },
        {
          id: 'Satsuki_Asui',
          name: 'Satsuki Asui',
        },
      ],
    },
    {
      id: 'Bibimi_Kenranzaki',
      name: 'Bibimi Kenranzaki',
      alias: null,
      affiliation: 'U.A. High School',
      birthday: 'March 5',
      bloodtype: null,
      description:
        "Bibimi Kenranzaki (絢 (けん) 爛 (らん) 崎 (ざき) 美 (び) 々 (び) 美 (み) , Kenranzaki Bibimi?) is a student of U.A. High School's Department of Support from Class 3-G and is the two-time winner of the U.A. School Festival's Miss Con.",
      fightstyle: null,
      gender: 'Female',
      Eye: null,
      hair: 'Blonde',
      height: '160 cm',
      kanji: '絢 (けん) 爛 (らん) 崎 (ざき) 美 (び) 々 (び) 美 (み) ',
      occupation: 'Student',
      quirk: null,
      romaji: 'Kenranzaki Bibimi',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bibimi_Kenranzaki-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bibimi_Kenranzaki-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bibimi_Kenranzaki.jpg',
      ],
      epithet: null,
      ages: [
        {
          age: '17[1] ',
          when: 'First Appearance',
        },
        {
          age: '18 ',
          when: 'Current',
        },
      ],
      family: null,
    },
    {
      id: 'Bigshot',
      name: 'Bigshot',
      alias: null,
      affiliation: null,
      birthday: null,
      bloodtype: null,
      description:
        'Bigshot (ビッグショット, Biggushotto?) is a character of the spin-off My Hero Academia: Vigilantes. He is a Pro Hero and a sidekick of Ingenium.',
      fightstyle: null,
      gender: 'Male',
      Eye: null,
      hair: null,
      height: null,
      kanji: 'ビッグショット',
      occupation: 'Pro Hero',
      quirk: null,
      romaji: 'Biggushotto',
      status: 'Alive',
      teams: 'Team Idaten',
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bigshot-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bigshot.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Bombers',
      name: 'Bombers',
      alias: 'Bomber',
      affiliation: 'Villain Factory',
      birthday: null,
      bloodtype: null,
      description:
        'Bombers were a group of bat-winged Next-Level Villains created by the Villain Factory to act as suicide bombs. They were used by Number 6 to attack specific targets. They appear in My Hero Academia: Vigilantes.',
      fightstyle: null,
      gender: null,
      Eye: null,
      hair: null,
      height: null,
      kanji: null,
      occupation: 'Next-Level Villains',
      quirk: null,
      romaji: null,
      status: 'Deceased',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Bombers-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Bombers.jpg',
      ],
      epithet: 'Exploding Villains',
      ages: null,
      family: null,
    },
    {
      id: 'Camie_Utsushimi',
      name: 'Camie Utsushimi',
      alias: 'Maboromicamie',
      affiliation: 'Shiketsu High School',
      birthday: 'August 15',
      bloodtype: 'O',
      description:
        'Camie Utsushimi (現 (うつし) 見 (み) ケミィ, Utsushimi Kemyi?), also known as Maboromicamie (マボロミケミィ, Maboromikemyi?), is a second-year student at Shiketsu High School training to become a Pro Hero. \nDuring the Provisional Hero License Exam, she was impersonated by Himiko Toga.',
      fightstyle: null,
      gender: 'Female',
      Eye: 'Dark Brown',
      hair: 'Fawn',
      height: '161 cm (5’3”)',
      kanji: '現 (うつし) 見 (み) ケミィ',
      occupation: 'Student',
      quirk: 'Glamour',
      romaji: 'Utsushimi Kemyi',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Camie_Utsushimi-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Camie_Utsushimi-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Camie_Utsushimi.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Chikara_Yotsubashi',
      name: 'Chikara Yotsubashi',
      alias: 'Destro',
      affiliation: 'Meta Liberation Army',
      birthday: null,
      bloodtype: null,
      description:
        'Chikara Yotsubashi (四 (よ) ツ橋 (ばし) 主税 (ちから) , Yotsubashi Chikara?), also known as Destro (デストロ, Desutoro?), was an infamous villain and the grand commander and founder of the original Meta Liberation Army.[3] He was the father of Rikiya Yotsubashi.',
      fightstyle: null,
      gender: 'Male',
      Eye: 'Dark Brown',
      hair: 'Light Brown',
      height: null,
      kanji: '四 (よ) ツ橋 (ばし) 主税 (ちから) ',
      occupation: 'Villain, Grand commander of the Meta Liberation Army',
      quirk: null,
      romaji: 'Yotsubashi Chikara',
      status: 'Deceased',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Chikara_Yotsubashi-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chikara_Yotsubashi-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chikara_Yotsubashi.jpg',
      ],
      epithet: null,
      ages: null,
      family: [
        {
          id: 'The_Mother_of_Quirks',
          name: 'Unnamed Mother',
        },
        {
          id: '#cite_note-ch232-0',
          name: '[1]',
        },
        {
          id: 'Rikiya_Yotsubashi',
          name: 'Rikiya Yotsubashi',
        },
      ],
    },
    {
      id: 'Chikuchi_Togeike',
      name: 'Chikuchi Togeike',
      alias: null,
      affiliation: 'U.A. High School',
      birthday: null,
      bloodtype: null,
      description:
        "Chikuchi Togeike (棘 (とげ) 池 (いけ) 築 (ちく) 稚 (ち) , Togeike Chikuchi?) is a student in U.A. High School's General Department.",
      fightstyle: null,
      gender: 'Female',
      Eye: 'Dark Brown',
      hair: 'Dark Brown',
      height: null,
      kanji: '棘 (とげ) 池 (いけ) 築 (ちく) 稚 (ち) ',
      occupation: 'Student',
      quirk: null,
      romaji: 'Togeike Chikuchi',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Chikuchi_Togeike-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chikuchi_Togeike.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Chitose_Kizuki',
      name: 'Chitose Kizuki',
      alias: 'Curious',
      affiliation: 'Meta Liberation Army',
      birthday: null,
      bloodtype: null,
      description:
        'Chitose Kizuki (気 (き) 月 (づき) 置 (ち) 歳 (とせ) , Kidzuki Chitose?) also known by the code name Curious (キュリオス, Kyuriosu?), was the executive director of Shoowaysha Publishing who was also secretly a leading member of the modern Meta Liberation Army. She is one of the main antagonists of the Meta Liberation Army Arc.',
      fightstyle: null,
      gender: 'Female',
      Eye: 'Green irises, Black sclera',
      hair: 'Lilac',
      height: null,
      kanji: '気 (き) 月 (づき) 置 (ち) 歳 (とせ) ',
      occupation: 'Villain, Executive',
      quirk: 'Landmine',
      romaji: 'Kidzuki Chitose',
      status: 'Deceased',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Chitose_Kizuki-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chitose_Kizuki.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
    {
      id: 'Chiyo_Shuzenji',
      name: 'Chiyo Shuzenji',
      alias: 'Youthful Heroine: Recovery Girl',
      affiliation: 'U.A. High School',
      birthday: 'April 4th',
      bloodtype: 'B',
      description:
        'Chiyo Shuzenji (修 (しゅう) 善 (ぜん) 寺 (じ) 治 (ち) 与 (よ) , Shūzenji Chiyo?), also known as Youthful Heroine: Recovery Girl (妙齢ヒロイン リカバリーガール, Myōrei Hiroin Rikabarī Gāru?),[2] is a nurse at U.A. High School. She has two offices; one located in U.A. High School and one in the Sports Festival Stadium.',
      fightstyle: null,
      gender: 'Female',
      Eye: null,
      hair: 'Gray',
      height: '115 cm',
      kanji: '修 (しゅう) 善 (ぜん) 寺 (じ) 治 (ち) 与 (よ) ',
      occupation: 'Nurse, Pro Hero',
      quirk: 'Heal',
      romaji: 'Shūzenji Chiyo',
      status: 'Alive',
      teams: null,
      images: [
        'https://storage.googleapis.com/my-hero-academia-api/Chiyo_Shuzenji-1.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chiyo_Shuzenji-2.jpg',
        'https://storage.googleapis.com/my-hero-academia-api/Chiyo_Shuzenji.jpg',
      ],
      epithet: null,
      ages: null,
      family: null,
    },
  ],
};
